language: python
env:
  global:
    - PATH=$PATH:/tmp/bin
  matrix:
    - BROWSER=firefox
    - BROWSER=chrome
    - REMOTE_ARG='--remote-url http://127.0.0.1:4444/wd/hub' BROWSER=firefox
python:
  - "2.6"
  - "2.7"
  #- "3.2" # Fails miserably in Python 3
install:
  - "python setup.py install"
  # Install the Selenium Server
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.26.0.jar -O selenium-server.jar"
  # Firefox is already installed
  # Install Google Chrome
  - "wget https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb"
  - "sudo apt-get install libgconf2-4"
  - "sudo dpkg -i google-chrome*.deb"
  - "sudo apt-get -f install" # reported dependency issue?
  # Install the Google Chrome webdriver
  - "mkdir /tmp/bin"
  - "wget https://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip"
  - "unzip chromedriver_linux32_23.0.1240.0.zip"
  - "mv chromedriver /tmp/bin"
  # Remove after 4814 is resolved
  # http://code.google.com/p/selenium/issues/detail?id=4814
  - "wget http://download.cdn.mozilla.net/pub/mozilla.org/firefox/releases/16.0/linux-i686/en-US/firefox-16.0.tar.bz2"
  - "tar -xjf firefox-16.0.tar.bz2"
  - "export PATH=./firefox:$PATH"

before_script:
  # Setup headless X per http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "java -jar selenium-server.jar > /dev/null &"
  - "sleep 30"
script:
  - "salad --browser $BROWSER $REMOTE_ARG salad/features --verbosity=2"
